### ISSUE TITLE
Segmentation Fault when calling "write bmad"

### ISSUE THREAD

**Issue by ColwynGulliford** [DavidSagan/Bmad#375]
When trying to write an injector lattice from Tao using the "write bmad" command, I'm getting a segmentation fault:

```
Tao> write bmad test/lat.bmad
corrupted double-linked list

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f3737f21d4f in ???
#1  0x7f3737f21cbb in ???
#2  0x7f3737f23354 in ???
#3  0x7f3737f67ae6 in ???
#4  0x7f3737f6fb69 in ???
#5  0x7f3737f703fb in ???
#6  0x7f3737f7322d in ???
#7  0x7f3737f74617 in ???
#8  0x56476a54891e in ???
#9  0x56476a4dabe0 in ???
#10  0x56476a312b5d in ???
#11  0x56476a251846 in ???
#12  0x56476a009dfd in ???
#13  0x56476a0074e7 in ???
#14  0x56476a0071c7 in ???
#15  0x7f3737f0c29c in ???
#16  0x56476a0071f8 in ???
Aborted
```

Attached is a minimal working example.

[inv1.tgz](https://github.com/DavidSagan/Bmad/files/11239680/inv1.tgz)

**Comment by ColwynGulliford** [comment]
This is using Bmad via condo: 

bmad 20230414.1
